---
# tasks file for omsagentlinux
- name: Check whether OMS agent is already installed
  stat:
    path: "{{ oms_agent_path }}"
  register: oms_agent_installed

- name: Download OMS agent
  get_url:
    url: "{{ url_omsagent }}"
    dest: /tmp/
    mode: 0755
  when: not oms_agent_installed.stat.exists or purge_oms_config

- name: Purge any existing configuration for the OMS agent
  shell: "/tmp/onboard_agent.sh --purge"
  when: purge_oms_config

- name: Install OMS agent
  shell: "/tmp/onboard_agent.sh -w {{ workspace_id }} -s {{ workspace_key }}"
  when: not oms_agent_installed.stat.exists or purge_oms_config

- name: Install deamon
  shell: "/opt/microsoft/omsagent/bin/service_control restart {{ workspace_id }}"
  when: not oms_agent_installed.stat.exists or purge_oms_config

- name: Remove OMS agent installer
  file: path=/tmp/onboard_agent.sh state=absent

- name: Check wheter Dependency agent is already installed
  stat:
    path: "{{ dependency_agent_path }}"
  register: dependency_agent_installed

- name: Download dependency agent
  get_url:
    url:  "{{ url_dependencyagent }}"
    dest: /tmp/InstallDependencyAgent-Linux64.bin
    mode: 0755
  when: not dependency_agent_installed.stat.exists

- name: Install dependency agent
  shell: "/tmp/InstallDependencyAgent-Linux64.bin -s"
  when: not dependency_agent_installed.stat.exists

- name: Remove Dependency agent installer
  file: path=/tmp/InstallDependencyAgent-Linux64.bin state=absent